# Generated by Django 3.0.6 on 2020-08-06 20:55

import crm_accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_clients_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('client_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('extimate_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('estimate_id', models.CharField(default=crm_accounts.models.ran_gen, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=100)),
                ('discount', models.FloatField(blank=True, default=0, max_length=100, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Clients')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('purchase_from', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_by', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('paid_by', models.CharField(choices=[('ca', 'Cash'), ('tf', 'Tranfer'), ('bd', 'Bank Deposit'), ('ch', 'Cheque'), ('ot', 'Ot')], max_length=2)),
                ('status', models.CharField(choices=[('pd', 'Pending'), ('ap', 'Approved')], max_length=2)),
                ('attachement', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_percentage', models.IntegerField()),
                ('tax_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidentFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_share_amount', models.IntegerField(verbose_name='Employee Share(amount)')),
                ('company_share_amount', models.IntegerField(verbose_name='Company Share(amount)')),
                ('employee_share', models.IntegerField(verbose_name='Employee Share(%)')),
                ('company_share', models.IntegerField(verbose_name='Company Share(%)')),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('provident_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm_accounts.ProvidentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='')),
                ('item_description', models.CharField(max_length=200, verbose_name='')),
                ('unit_cost', models.IntegerField(verbose_name='')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('total', models.IntegerField(default=0)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_accounts.Estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('client_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('invoice_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('item_name', models.CharField(max_length=200, verbose_name='')),
                ('item_description', models.CharField(max_length=200, verbose_name='')),
                ('unit_cost', models.IntegerField(verbose_name='')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('amount', models.IntegerField(verbose_name='')),
                ('invoice_id', models.CharField(default=crm_accounts.models.ran_gen, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=100)),
                ('discount', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('other_information', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Clients')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects')),
                ('taxes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_accounts.Taxes')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='taxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_accounts.Taxes'),
        ),
    ]
