# Generated by Django 3.0.5 on 2020-08-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0002_auto_20200805_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='discount',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
