# Generated by Django 3.0.5 on 2020-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0002_auto_20200723_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='Wfx8G', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='lx6UM', max_length=10, unique=True),
        ),
    ]
