# Generated by Django 3.0.5 on 2020-07-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0002_auto_20200728_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='3pZRu', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='u6ZjF', max_length=10, unique=True),
        ),
    ]
