# Generated by Django 3.0.5 on 2020-08-19 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0002_auto_20200818_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InoviceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='')),
                ('item_description', models.CharField(max_length=200, verbose_name='')),
                ('unit_cost', models.IntegerField(verbose_name='')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('total', models.IntegerField(default=0)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_accounts.Invoice')),
            ],
        ),
    ]
