# Generated by Django 3.0.5 on 2020-08-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0002_auto_20200811_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='tax_percentage',
            field=models.FloatField(),
        ),
    ]
