# Generated by Django 3.0.6 on 2020-08-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0003_auto_20200807_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
