# Generated by Django 3.0.5 on 2020-07-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0003_auto_20200731_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='7pr8l', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='8xWfb', max_length=10, unique=True),
        ),
    ]
