# Generated by Django 3.0.5 on 2020-08-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0003_auto_20200811_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='unit_cost',
        ),
        migrations.CreateModel(
            name='InoviceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='')),
                ('item_description', models.CharField(max_length=200, verbose_name='')),
                ('unit_cost', models.IntegerField(verbose_name='')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('total', models.IntegerField(default=0)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_accounts.Invoice')),
            ],
        ),
    ]
