# Generated by Django 3.0.5 on 2020-08-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0004_auto_20200808_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='paid_by',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Tranfer'), ('bank deposit', 'Bank Deposit'), ('cheque', 'Cheque'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(choices=[('inspect', 'Inspect'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
