# Generated by Django 3.0.5 on 2020-08-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0004_auto_20200819_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
    ]
