# Generated by Django 3.0.5 on 2020-07-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0004_auto_20200731_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='QvGu7', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='n1SFN', max_length=10, unique=True),
        ),
    ]
