# Generated by Django 3.0.5 on 2020-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0005_remove_invoice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
