# Generated by Django 3.0.5 on 2020-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0005_auto_20200803_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='ahpEeF', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='CUtneU', max_length=10, unique=True),
        ),
    ]
