# Generated by Django 3.0.5 on 2020-08-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0005_auto_20200808_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
    ]
