# Generated by Django 3.0.5 on 2020-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0008_auto_20200804_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='xb97gJ', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('ca', 'Cash'), ('tf', 'Tranfer'), ('bd', 'Bank Deposit'), ('ch', 'Cheque'), ('ot', 'Ot')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(blank=True, choices=[('pd', 'Pending'), ('ap', 'Approved')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='SfrpQF', max_length=10, unique=True),
        ),
    ]
