# Generated by Django 3.0.6 on 2020-08-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0008_auto_20200802_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='8yRU9', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='FnWBN', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='')),
                ('item_description', models.CharField(max_length=200, verbose_name='')),
                ('unit_cost', models.IntegerField(verbose_name='')),
                ('quantity', models.IntegerField(verbose_name='')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_accounts.Estimate')),
            ],
        ),
    ]
