# Generated by Django 3.0.6 on 2020-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0009_auto_20200805_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='RdgWt', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='ezklO', max_length=10, unique=True),
        ),
    ]
