# Generated by Django 3.0.5 on 2020-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0009_auto_20200804_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='HAp6yd', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('Cash', 'cash'), ('Tranfer', 'tranfer'), ('Bank Deposit', 'bank_deposit'), ('Cheque', 'cheque'), ('Others', 'Others')], default='inspect', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(blank=True, choices=[('Inspect', 'inspect'), ('Approved', 'approved'), ('Rejected', 'Rejected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='3DlfCl', max_length=10, unique=True),
        ),
    ]
