# Generated by Django 3.0.5 on 2020-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0010_auto_20200805_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='tifvS1', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('Cash', 'cash'), ('Transfer', 'transfer'), ('Bank Deposit', 'bank_deposit'), ('Cheque', 'cheque'), ('Others', 'Others')], default='inspect', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='7ejeBu', max_length=10, unique=True),
        ),
    ]
