# Generated by Django 3.0.6 on 2020-08-05 17:48

import crm_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0010_auto_20200805_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default=crm_accounts.models.ran_gen, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=crm_accounts.models.ran_gen, max_length=10, unique=True),
        ),
    ]
