# Generated by Django 3.0.5 on 2020-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0011_auto_20200805_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='xoiuzg', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('Cash', 'cash'), ('Tranfer', 'transfer'), ('Bank Deposit', 'bank_deposit'), ('Cheque', 'cheque'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(choices=[('inspect', 'Inspect'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='inspect', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='knIyMa', max_length=10, unique=True),
        ),
    ]
