# Generated by Django 3.0.5 on 2020-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0020_auto_20200603_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='rKS2a', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='TPqL6', max_length=10, unique=True),
        ),
    ]
