# Generated by Django 3.0.5 on 2020-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0035_auto_20200612_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='Hgy4L', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='cWGmJ', max_length=10, unique=True),
        ),
    ]
