# Generated by Django 3.0.5 on 2020-06-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0039_auto_20200612_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='TcIJS', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='K4DVD', max_length=10, unique=True),
        ),
    ]
