# Generated by Django 3.0.5 on 2020-06-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0046_auto_20200612_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='8ev2t', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='K1o2s', max_length=10, unique=True),
        ),
    ]
