# Generated by Django 3.0.5 on 2020-06-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0064_auto_20200614_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='q3mzP', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='4dCLD', max_length=10, unique=True),
        ),
    ]
