# Generated by Django 3.0.6 on 2020-07-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0074_auto_20200617_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='XKm4k', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='4bLqa', max_length=10, unique=True),
        ),
    ]
