# Generated by Django 3.0.6 on 2020-07-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0083_auto_20200720_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='GUOOw', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='Ml0bf', max_length=10, unique=True),
        ),
    ]
