# Generated by Django 3.0.6 on 2020-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0084_auto_20200725_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_id',
            field=models.CharField(default='DYA9K', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='9bBlf', max_length=10, unique=True),
        ),
    ]
