# Generated by Django 3.0.5 on 2020-08-17 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='assets',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
