# Generated by Django 3.0.5 on 2020-06-05 11:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clocking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clocking',
            name='clockin_time',
        ),
        migrations.RemoveField(
            model_name='clocking',
            name='clockout_time',
        ),
        migrations.RemoveField(
            model_name='clocking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='clocking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='clocking',
            name='month',
        ),
        migrations.RemoveField(
            model_name='clocking',
            name='week',
        ),
        migrations.RemoveField(
            model_name='clocking',
            name='year',
        ),
        migrations.AddField(
            model_name='clocking',
            name='clockin_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
    ]
