# Generated by Django 3.0.6 on 2020-07-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200608_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
