# Generated by Django 3.0.6 on 2020-08-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200801_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
