# Generated by Django 3.0.5 on 2020-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200811_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_start_date',
            field=models.DateField(),
        ),
    ]
