# Generated by Django 3.0.6 on 2020-08-02 21:27

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default=employees.models.generate_emp_id, max_length=20, unique=True),
        ),
    ]
