# Generated by Django 3.0.5 on 2020-06-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_attendance_clock_ins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendace',
            new_name='attendance',
        ),
    ]
