# Generated by Django 3.0.6 on 2020-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200607_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
