# Generated by Django 3.0.6 on 2020-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_staff_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
