# Generated by Django 3.0.6 on 2020-07-31 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20200731_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='joined',
        ),
    ]
