# Generated by Django 3.0.5 on 2020-08-25 23:36

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_logo', models.ImageField(upload_to='invoices')),
            ],
            options={
                'verbose_name': 'Invoice Settings',
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_country', django_countries.fields.CountryField(max_length=2)),
                ('date_format', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Africa/Lagos')),
                ('default_language', models.CharField(blank=True, choices=[('eng', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='eng', max_length=100, null=True)),
                ('currency_code', models.CharField(blank=True, choices=[('naira', 'Naira'), ('USD', 'USD'), ('pound', 'Pound'), ('euro', 'EURO')], default='naira', max_length=100, null=True)),
                ('currency_symbol', models.CharField(blank=True, choices=[('₦', '₦'), ('$', '$'), ('€', '€'), ('£', '£')], default='₦', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Localization',
                'verbose_name_plural': 'Localizations',
            },
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Module Access',
                'verbose_name_plural': 'Module Access',
            },
        ),
        migrations.CreateModel(
            name='SalarySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da', models.IntegerField(blank=True)),
                ('hra', models.IntegerField(blank=True)),
                ('provident_fund', models.IntegerField(blank=True)),
                ('esi_settings', models.IntegerField(blank=True)),
                ('organisation_share', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Salary Settings',
                'verbose_name_plural': 'Salary Settingss',
            },
        ),
        migrations.CreateModel(
            name='SMTPEmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=150)),
                ('smtp_user', models.CharField(blank=True, max_length=150)),
                ('smtp_password', models.CharField(blank=True, max_length=150)),
                ('smtp_port', models.CharField(max_length=150)),
                ('smtp_security', models.CharField(blank=True, choices=[('none', 'NONE'), ('ssl', 'SSL'), ('tls', 'TLS')], max_length=150)),
                ('smtp_auth_domain', models.CharField(blank=True, max_length=150, verbose_name='SMTP Authentication Domain')),
            ],
            options={
                'verbose_name': 'SMTP Email Settings',
                'verbose_name_plural': 'SMTP Email Settingss',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(upload_to='company')),
                ('favicon', models.ImageField(upload_to='company')),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
