# Generated by Django 3.0.5 on 2020-05-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='CompanyInfo',
        ),
    ]
