# Generated by Django 3.0.5 on 2020-08-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='Country',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
