# Generated by Django 3.0.5 on 2020-08-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200814_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
