# Generated by Django 3.0.6 on 2020-07-19 20:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=20)),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('draft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messaging.MailBody')),
            ],
        ),
    ]
