# Generated by Django 3.0.5 on 2020-07-28 21:50

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.IntegerField()),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('open_ed', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.ManyToManyField(related_name='mail_body', to='messaging.MailBody')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messaging.MailBody')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document/')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.MailBody')),
            ],
        ),
    ]
