# Generated by Django 3.0.5 on 2020-08-03 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mail',
            name='body',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messaging.MailBody'),
        ),
        migrations.AddField(
            model_name='files',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.MailBody'),
        ),
    ]
