# Generated by Django 3.0.6 on 2020-07-20 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20200719_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbody',
            name='cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
