# Generated by Django 3.0.6 on 2020-07-20 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20200720_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbody',
            name='cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
