# Generated by Django 3.0.6 on 2020-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20200720_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document/')),
            ],
        ),
        migrations.AlterField(
            model_name='mailbody',
            name='from_email',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='mailbody',
            name='files',
            field=models.ManyToManyField(to='messaging.Files'),
        ),
    ]
