# Generated by Django 3.0.6 on 2020-07-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20200720_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbody',
            name='files',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document/')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.MailBody')),
            ],
        ),
    ]
