# Generated by Django 3.0.6 on 2020-07-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_mailbody_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbody',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
