# Generated by Django 3.0.6 on 2020-07-25 16:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20200720_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbody',
            name='open_ed',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
