# Generated by Django 3.0.6 on 2020-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_mailbody_open_ed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbody',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
