# Generated by Django 3.0.5 on 2020-06-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
