# Generated by Django 3.0.5 on 2020-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='end_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='start_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
