# Generated by Django 3.0.5 on 2020-06-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200614_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracker',
            name='status',
            field=models.CharField(choices=[('pause', 'pause'), ('working', 'Working'), ('terminate', 'Terminate')], default='working', max_length=10),
        ),
    ]
