# Generated by Django 3.0.5 on 2020-06-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktracker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='status',
            field=models.CharField(choices=[('pause', 'pause'), ('working', 'Working'), ('terminate', 'Terminate')], default='pause', max_length=10),
        ),
    ]
