# Generated by Django 3.0.5 on 2020-06-15 13:23

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200614_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(default=tasks.models.generate_task_id, max_length=10, unique=True),
        ),
    ]
