# Generated by Django 3.0.5 on 2020-08-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200818_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('cancelled', 'cancelled')], max_length=50),
        ),
    ]
