# Generated by Django 3.0.5 on 2020-07-31 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200731_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Clients'),
        ),
    ]
