# Generated by Django 3.0.5 on 2020-05-29 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_auto_20200523_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='team_member',
        ),
        migrations.AddField(
            model_name='projects',
            name='team_member',
            field=models.ManyToManyField(blank=True, related_name='team_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
