# Generated by Django 3.0.5 on 2020-06-12 20:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200612_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=''), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=''), blank=True, null=True, size=None),
        ),
    ]
