# Generated by Django 3.0.5 on 2020-06-12 20:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200612_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=''), default=list, size=None),
        ),
    ]
