# Generated by Django 3.0.5 on 2020-06-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20200612_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
