# Generated by Django 3.0.5 on 2020-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_docupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docupload',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
