# Generated by Django 3.0.5 on 2020-06-15 13:23

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20200614_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_id',
            field=models.CharField(default=project.models.generate_project_id, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='clients_id',
            field=models.CharField(default=project.models.generate_client_id, max_length=20, unique=True),
        ),
    ]
