# Generated by Django 3.0.5 on 2020-06-16 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200615_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
