# Generated by Django 3.0.5 on 2020-06-17 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0024_auto_20200616_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='milestone_assignes',
            field=models.ManyToManyField(blank=True, null=True, related_name='milestone_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='milestone_followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='milestone_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
