# Generated by Django 3.0.5 on 2020-06-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20200617_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='assigned_to',
        ),
    ]
