# Generated by Django 3.0.6 on 2020-07-19 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0026_remove_milestone_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone_assignes',
            field=models.ManyToManyField(related_name='milestone_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='milestone_followers',
            field=models.ManyToManyField(related_name='milestone_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
